-- MySQL Script generated by MySQL Workbench
-- Thu Sep 10 13:30:42 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema movetrack
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `movetrack` ;

-- -----------------------------------------------------
-- Schema movetrack
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `movetrack` DEFAULT CHARACTER SET utf8 ;
USE `movetrack` ;

-- -----------------------------------------------------
-- Table `movetrack`.`countries`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movetrack`.`countries` ;

CREATE TABLE IF NOT EXISTS `movetrack`.`countries` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `slug` VARCHAR(15) NULL,
  `code` VARCHAR(5) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `movetrack`.`cities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movetrack`.`cities` ;

CREATE TABLE IF NOT EXISTS `movetrack`.`cities` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `slug` VARCHAR(15) NULL,
  `country_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cities_countries_idx` (`country_id` ASC),
  CONSTRAINT `fk_cities_countries`
    FOREIGN KEY (`country_id`)
    REFERENCES `movetrack`.`countries` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `movetrack`.`quaters`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movetrack`.`quaters` ;

CREATE TABLE IF NOT EXISTS `movetrack`.`quaters` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `slug` VARCHAR(15) NULL,
  `city_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_quaters_cities1_idx` (`city_id` ASC),
  CONSTRAINT `fk_quaters_cities1`
    FOREIGN KEY (`city_id`)
    REFERENCES `movetrack`.`cities` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `movetrack`.`clients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movetrack`.`clients` ;

CREATE TABLE IF NOT EXISTS `movetrack`.`clients` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `birthday` DATE NULL,
  `email` VARCHAR(255) NULL,
  `phone_number` VARCHAR(15) NULL,
  `sector` VARCHAR(255) NULL,
  `landmark` VARCHAR(255) NULL,
  `particular_landmark` VARCHAR(255) NULL,
  `quater_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_clients_quaters1_idx` (`quater_id` ASC),
  CONSTRAINT `fk_clients_quaters1`
    FOREIGN KEY (`quater_id`)
    REFERENCES `movetrack`.`quaters` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `movetrack`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movetrack`.`roles` ;

CREATE TABLE IF NOT EXISTS `movetrack`.`roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `movetrack`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movetrack`.`users` ;

CREATE TABLE IF NOT EXISTS `movetrack`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `avatar` VARCHAR(255) NULL,
  `username` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `remember_token` VARCHAR(255) NULL,
  `client_id` INT NULL,
  `role_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_users_clients1_idx` (`client_id` ASC),
  INDEX `fk_users_roles1_idx` (`role_id` ASC),
  CONSTRAINT `fk_users_clients1`
    FOREIGN KEY (`client_id`)
    REFERENCES `movetrack`.`clients` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_users_roles1`
    FOREIGN KEY (`role_id`)
    REFERENCES `movetrack`.`roles` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `movetrack`.`categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movetrack`.`categories` ;

CREATE TABLE IF NOT EXISTS `movetrack`.`categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `movetrack`.`tracks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movetrack`.`tracks` ;

CREATE TABLE IF NOT EXISTS `movetrack`.`tracks` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `reference` VARCHAR(255) NULL,
  `designation` VARCHAR(45) NULL,
  `brand` VARCHAR(45) NULL,
  `budget` INT NULL,
  `real_price` INT NULL,
  `delivery_price` INT NULL,
  `status` ENUM('emit', 'in pending', 'success', 'decline') NULL,
  `description` LONGTEXT NULL,
  `created_date` DATETIME NULL,
  `delivery_date` DATETIME NULL,
  `category_id` INT NOT NULL,
  `client_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tracks_categories1_idx` (`category_id` ASC),
  INDEX `fk_tracks_clients1_idx` (`client_id` ASC),
  CONSTRAINT `fk_tracks_categories1`
    FOREIGN KEY (`category_id`)
    REFERENCES `movetrack`.`categories` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_tracks_clients1`
    FOREIGN KEY (`client_id`)
    REFERENCES `movetrack`.`clients` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `movetrack`.`images`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movetrack`.`images` ;

CREATE TABLE IF NOT EXISTS `movetrack`.`images` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `track_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_images_tracks1_idx` (`track_id` ASC),
  CONSTRAINT `fk_images_tracks1`
    FOREIGN KEY (`track_id`)
    REFERENCES `movetrack`.`tracks` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `movetrack`.`faq`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movetrack`.`faq` ;

CREATE TABLE IF NOT EXISTS `movetrack`.`faq` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `question` VARCHAR(255) NULL,
  `response` LONGTEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
